### ISSUE TITLE
[Bug] 1.20.2 error in log (but mod appears to work anyways)

### ISSUE THREAD

**Issue by MeeniMc** [Aton-Kish/your-reputation#36]
### Describe the bug

In game, the tooltip contains a warning that there was an error with the plugin, and to refer to the jade error log. 

Other than that, the mod functionality appears complete. 

The jade error log contains the following exception log. 

```
10/08/2023 - 00:09:53
null
java.lang.AbstractMethodError: Receiver class atonkish.reputation.ReputationPlugin$$Lambda$7870/0x000002068c697d70 does not define or inherit an implementation of the resolved method 'abstract void onTooltipCollected(snownee.jade.api.ui.IBoxElement, snownee.jade.api.Accessor)' of interface snownee.jade.api.callback.JadeTooltipCollectedCallback.
	at snownee.jade.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:223)
	at snownee.jade.util.ClientProxy.onClientTick(ClientProxy.java:139)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$dli000$fabric-lifecycle-events-v1$onEndTick(class_310.java:14606)
	at net.minecraft.class_310.method_1574(class_310.java:2007)
	at net.minecraft.class_310.method_1523(class_310.java:1237)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

### To Reproduce

1. Minecraft 1.20.2
2. Jade-1.20.2-fabric-12.1.3
3. your-reputation-0.2.4+jade.1.20
4. spawn a villager
5. attack the villager (without killing it, duh) 
6. point at the villager, it shows that the villager is not trusting anymore (-25 or something)
7. the tooltip also contains a warning about an error in jade plugins

### Expected behavior

No error is produced

**Comment by MeeniMc** [comment]
resolved in newer versions
